server:
        port:  8761
eureka:
  client:
      register-with-eureka: false
      fetch-registry:  false   #是否从Eureka server获取注册信息，默认为true;因为这是一个单节点Eureka server，不需要同步其他Eureka server节点的数据，故而设为false;
      serviceUrl:
              defaultZone:  http://localhost:8761/eureka/ #设置Eureka server 交互地址，查询服务与注册服务都需要这个地址，默认http://localhost:8761/rureka。多个地址可用“，”分隔
