spring:
    datasource:
       driver-calss-name: com.mysql.jdbc.Driver    #驱动类
       url: jdbc:mysql://127.0.0.1:3307/springcloud?buseUnicode=true&amp;characterEncoding=UTF-8        #数据库地址
       username: root
       password: root
       schema:  classpath:schema.sql
       data:  classpath:data.sql
    jpa:
        hibernate:
          ddl-auto: update
        show-sql: false
    application:
        name: provider    #用于指定到Eureka Server上的应用名称
eureka:
  client:
     serviceUrl:
          defaultZone: http://localhost:8761/eureka/
     instance:
          prefer-ip-adress: true  #用于将自己的ip注册到Eureka Server 上。如不配置该属性或设置为false,则表示注册微服务所在操作系统的hostname到Eureka Server
